spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false

security:
  jwt:
    secretKey: ${SECRET_KEY:9Sdyeei3eVadXxnGTxPXiTzgKVZth9p8Zwz9yCVr5JJLP2avvJ777}
    tokenExpirationTime: 1440
    refreshTokenExpTime: 1576800

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

swagger:
  serverBaseUrl: ${SWAGGER_SERVER_BASE_URL:http://localhost:8080}

springdoc:
  packagesToScan: com.erp

core:
  name: core
  userUrl: /v1/users
  userIdUrl: /v1/users/{userId}
  userStatusUrl: /v1/users/{userId}/statuses
  registrationUrl: /v1/users/registrations
  confirmationUrl: /v1/users/{userId}/confirmations
  userDetailsUrl: /v1/users/user-details
  tokenUrl: /v1/users/{userId}/tokens

media:
  name: media
  baseUrl: /v1/media
