spring:
  application:
    name: media
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8077

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

aws:
  s3:
    secret: ${AWS_ACCESS_SECRET}
    key: ${AWS_ACCESS_KEY}
    region: ${AWS_REGION:eu-west-2}
    bucket: erp-media-storage
    serviceEndpoint: ${AWS_SERVICE_ENDPOINT:https://s3.eu-west-2.amazonaws.com}
